export class UPServiceConfig{

  //首页策略相关功能code
  static readonly SY_CL_NSXJGC: string = 'gjd_sy_cl_nsxjgc';
  static readonly SY_CL_BXFC: string = 'gjd_sy_cl_bxfc';
  static readonly SY_CL_CDXH: string = 'gjd_sy_cl_cdxh';
  static readonly SY_CL_LTQB: string = 'gjd_sy_cl_ltqb';
  static readonly SY_CL_QSZS: string = 'gjd_sy_cl_qszs';
  static readonly SY_CL_ZYDGCL: string = 'gjd_sy_cl_zydgcl';
  static readonly SY_CL_PEGCL: string = 'gjd_sy_cl_pegcl';
}